<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>irule</string>
		<string>_irule.tcl</string>
	</array>
	<key>firstLineMatch</key>
	<string>^WHEN_</string>
	<key>foldingEndMarker</key>
	<string>^\s*\}</string>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>name</key>
	<string>iRule</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?&lt;=^|;)\s*((#))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.irule</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.irule</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>comment.line.number-sign.irule</string>
			<key>end</key>
			<string>\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\\\|\\\n)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.irule</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.name.function.irule</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(when)\s+([^\s]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.irule</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=|[\[{;])\s*(if|while|for|catch|return|break|continue|switch|exit|foreach)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.irule</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^|})\s*(then|elsif|else)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.irule</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>pumctuation.definition.variable.irule</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b\$\w+\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.irule</string>
	<key>uuid</key>
	<string>e7058651-8802-4348-bd4f-a13066a210b3</string>
</dict>
</plist>
